### ISSUE TITLE
Latest version is broken, 

### ISSUE THREAD

**Issue by yoanhg421** [vinayakkulkarni/v-tweakpane#1514]
forked your stakblitz demo updated to the latest version of your pacakage and it's doesnt load the inputs. 
types are also giving an error 

```
 There are types at 'c:/dev/Projects/node/tresjs/node_modules/v-tweakpane/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'v-tweakpane' library may need to update its package.json or typings.
```

https://stackblitz.com/edit/v-tweakpane-alp9fg?file=src%2FApp.vue,package.json

**Comment by vinayakkulkarni** [comment]
https://stackblitz.com/edit/v-tweakpane?file=src/App.vue

Updated with latest version!
